openapi: 3.0.0
info:
  title: BILL PAY Services
  version: 1.0.0
servers:
  - url: http://{{api_gateway_host}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: BILL_PAY_MICROSERVICES
  - name: BILL_PAY_MICROSERVICES > API_HEALTH
  - name: BILL_PAY_MICROSERVICES > CUSTOMER_SERVICE
  - name: BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
  - name: BILL_PAY_MICROSERVICES > BULK_PAYMENT_SERVICE
  - name: BILL_PAY_MICROSERVICES > BILLING_SERVICE
paths:
  /customer/actuator/health:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > API_HEALTH
      summary: USER_API_HEALTH
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/actuator/health:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > API_HEALTH
      summary: PAYMENT_API_HEALTH
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bulk_payment/actuator/health:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > API_HEALTH
      summary: BULK_PAYMENT_API_HEALTH
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /customer/api/v1/customer/:
    post:
      tags:
        - BILL_PAY_MICROSERVICES > CUSTOMER_SERVICE
      summary: Register Customer Details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: 'email@email.com'
                first_name: 'Vivek'
                last_name: 'Bhandarkar'
                dob : '10/03/1984'
                gender : 'male'
      responses:
        '201':
          description: User Registration Successful
          content:
            application/json: {}
  /customer/api/v1/customer/{id}:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > CUSTOMER_SERVICE
      summary: Fetch Customer details with {id}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/api/v1/wallet/{id}:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
      summary: READ_WALLET_DETAILS_BY_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/api/v1/wallet/{id}/balance:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
      summary: READ_WALLET_BALANCE_BY_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /payment/api/v1/wallet/{id}/top-up:
    post:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: TOP_UP WALLET ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                amount: '100'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /payment/api/v1/fund-transfer:
    post:
      tags:
        - BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
      summary: UTILITY_PAYMENT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                wallet_id: 2
                biller_account: 250
                amount: '100'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /bulk_payment/api/v1/fund-transfer:
    post:
      tags:
        - BILL_PAY_MICROSERVICES > BULK_PAYMENT_SERVICE
      summary: UTILITY_PAYMENT
      requestBody:
        content:
          application/csv:
            schema:
              type: string
              format: binary
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /bulk_payment/api/v1/fund-transfer/{id}:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BULK_PAYMENT_SERVICE
      summary: BULK_PAYMENT_STATUS_BY_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /billing/api/v1/billtype/:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: GET_ALL_BILL_TYPE
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /billing/api/v1/billtype/{id}:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: GET_ALL_BILL_TYPE_BY_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /billing/api/v1/billtype/{id}/biller:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: GET_ALL_BILLER_INFO_BY_BILL_TYPE_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /billing/api/v1/biller/{biller_id}:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: GET_ALL_BILLER_INFO_BY_BILL_INFO_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /billing/api/v1/biller/{biller_id}/metadata:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > BILLING_SERVICE
      summary: GET_ALL_BILLER_CUSTOMER_REGISTRATION_METADATA_BY_BILLER_INFO_ID
      responses:
        '200':
          description: Successful response
          content:
            application/json: { }
  /billing/api/v1/register-bill-customer:
    post:
      tags:
        - BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
      summary: UTILITY_PAYMENT
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                customer_id: 2
                biller_id: 250
                biller_customer_id: 'XZ100'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /billing/api/v1/biller_customer_registrations/{id}/bill:
    get:
      tags:
        - BILL_PAY_MICROSERVICES > PAYMENT_SERVICE
      summary: UTILITY_PAYMENT
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}